require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'Hud' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    # Use node/require to resolve expo-modules-autolinking from expo's path (fixes React header import issues)
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Fix React-Core umbrella: remove headers that don't exist or break Swift/ObjC module build.
    # CoreModulesPlugins.h is internal to React-CoreModules. *+Internal.h are private and not shipped.
    # Without this, Swift "import React" and ExpoModulesCore fail with "file not found".
    umbrella_paths = [
      File.join(installer.sandbox.root, 'Target Support Files', 'React-Core', 'React-Core-umbrella.h'),
      File.join(installer.sandbox.root, 'Headers', 'Public', 'React', 'React-Core-umbrella.h'),
      File.join(installer.sandbox.root, 'Headers', 'Public', 'React-Core', 'React-Core-umbrella.h'),
    ]
    # Headers from React-Core header_subspecs (CoreModules, Libraries/*) - they live in
    # separate pods (React-CoreModules, React-RCTActionSheet, etc.) and break Swift module build.
    problematic_patterns = [
      'CoreModulesPlugins.h',
      '+Internal.h',
      'RCTAccessibilityManager.h',
      'RCTActionSheetManager.h',
      'RCTAlertController.h',
      'RCTAlertManager.h',
      'RCTAppState.h',
      'RCTClipboard.h',
      'RCTDevLoadingView.h',
      'RCTDevMenu.h',
      'RCTDevSettings.h',
      'RCTEventDispatcher.h',
      'RCTExceptionsManager.h',
      'RCTKeyboardObserver.h',
      'RCTLogBox',
      'RCTPlatform.h',
      'RCTSourceCode.h',
      'RCTStatusBarManager.h',
      'RCTTiming.h',
      'RCTWebSocketModule.h',
      'RCTBlobManager.h',
      'RCTFileReaderModule.h',
      'RCTLinkingManager.h',
      'RCTNetworking.h',
      'RCTSettingsManager.h',
      'RCTVibration.h',
      'RCTPushNotification',
    ]
    umbrella_paths.each do |react_core_umbrella|
      next unless File.exist?(react_core_umbrella)
      umbrella_content = File.read(react_core_umbrella)
      original = umbrella_content.dup
      umbrella_content = umbrella_content.lines.reject do |line|
        problematic_patterns.any? { |p| line.include?(p) }
      end.join
      if umbrella_content != original
        File.write(react_core_umbrella, umbrella_content)
        Pod::UI.puts "Patched React-Core umbrella: removed problematic header imports".green
      end
    end
  end
end


# apple-targets-extension-loader -- Dynamic loading of target configurations
Dir.glob(File.join(__dir__, '..', 'targets', '**', 'pods.rb')).each do |target_file|
  target_name = File.basename(File.dirname(target_file))
  target target_name do
    # Create a new binding with access to necessary methods and variables
    target_binding = binding
    target_binding.local_variable_set(:podfile_properties, podfile_properties)

    # Evaluate the target file content in the new binding
    eval(File.read(target_file), target_binding, target_file)
  end
end
